### ISSUE TITLE
UnicodeDecodeError: 'cp950' codec can't decode byte 0x86 in position 19: illegal multibyte sequence

### ISSUE THREAD

**Issue by Arcelibs** [overflow65537/Tkinter_MAA-GUI#1]
C:\Users\fw\Downloads\MAA-GUI>main.exe
Traceback (most recent call last):
  File "main.py", line 6, in <module>
  File "ui.py", line 299, in __init__
  File "control.py", line 57, in init
  File "json\__init__.py", line 293, in load
UnicodeDecodeError: 'cp950' codec can't decode byte 0x86 in position 19: illegal multibyte sequence
[3480] Failed to execute script 'main' due to unhandled exception!

Win10繁中OS執行出現此錯誤

**Comment by overflow65537** [comment]
我的问题,后面添加的几个open()没标记编码格式
现在应该是解决了
